apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-deploy"
  labels: 
    app: "{{ .Release.Name }}-deploy"
spec: 
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      project: {{ .Release.Name }}
  template:
    metadata:
      labels: 
        project: {{ .Release.Name }}
    spec:
      containers:
        - name: "{{ .Release.Name }}-web" 
          image: {{ .Values.container.image }}
          imagePullPolicy: Always
          ports: 
            - containerPort: 9090
