apiVersion: v1
kind: Service
metadata: 
  name: "{{ .Release.Name }}-load"
  labels:
    app: "{{ .Release.Name }}-deploy"
spec:
  selector: 
    app: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      name: {{ .Release.Name }}
  type: LoadBalancer